[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amap = "0.1.2"
itertools = "0.12.0"
memchr = "2.6.4"
[profile.release]
lto = true
codegen-units = 1
debug = true
